Adapt to new global neutron upper constraint
Neutron was added to upper constraints in openstack/requirements
stable branches (I8e95dc48b8ba2a7e16f1d34eb5ad0e87a3e96f4f), which
causes failure due to conflict with tox targets installing neutron
directly from git:

ERROR: Could not satisfy constraints for 'neutron': installation from path or url cannot be constrained to a version

Most of the zuul templates used in the .zuul.yaml marks neutron as
required project except lower-constraint job. Let's make that also
install neutron. Also add neutron to requirements.txt.

Note(elod.illes): by removing editable git installation of neutron from
tox and adding it to requirements.txt involves that tests in Zuul will
run against latest stable state, but locally the test will run against
latest release from stable/* of neutron. So in short: they test
different things.

Conflicts:
    tox.ini

Note(elod.illes): conflict is due to upper-constraints.txt link is
different in every stable branch.
Some other changes compared to original version:
* neutron version had to be updated to Stein in lower-constraints.txt
  and requirements.txt
* omit cap of hacking, since it was already introduced in a previous
  patch
* Change ID needed to be changed, since an earlier version of the
  original backport got merged.

(cherry picked from commit a00fc731b14bd3ef953fe4cffdc74c8e441c0e13)
(cherry picked from commit cfa217e9b1c9a346b2e7165110e4195d773268f3)

Change-Id: Id76dcad7d2c1e6810df2e84b25258c77c5d3e616