Adjust version constraint of hacking
Neutron constrained the version of hacking < 1.2.0, but since then the
unit tests fails with:

ERROR: Double requirement given: hacking<1.2.0,>=1.1.0 (from -ri https://opendev.org/openstack/neutron/raw/branch/master/test-requirements.txt (line 4)) (already in hacking>=1.1.0 (from -r [..]networking-powervm/test-requirements.txt (line 4)), name='hacking')

So let's simply use the same constraint as set in neutron.

Change-Id: Ic4d97db6c947264806e5ef9e35f21f764cbecf46