Cap hacking, add bindep.txt and update sphinx requirement
This is a combination of 3 fixes, which are all needed to fix the gate.

1. Adjust version constraint of hacking

Neutron constrained the version of hacking < 1.2.0, but since then the
unit tests fails with:

ERROR: Double requirement given: hacking<1.2.0,>=1.1.0 (from -ri https://opendev.org/openstack/neutron/raw/branch/master/test-requirements.txt (line 4)) (already in hacking>=1.1.0 (from -r [..]networking-powervm/test-requirements.txt (line 4)), name='hacking')

So let's simply use the same constraint as set in neutron.

2. Add bindep.txt

...to fix building lxml

(cherry picked from commit ed11ef916d415ea060ca92afa0521f863714ffec)

3. Update sphinx version constraints

Since we touch requirements file with this patch the requirements-check
job also runs and does not find the matching python2 and python3 sphinx
requirements, so update that.

NOTE(elod.illes): libz-dev binary dependency also needed otherwise
lower-constraints target fails.

Change-Id: Ic4d97db6c947264806e5ef9e35f21f764cbecf46
(cherry picked from commit a00fc731b14bd3ef953fe4cffdc74c8e441c0e13)
(cherry picked from commit 032cd43638fa190aa26ca564b71f293de7a74bb9)
(cherry picked from commit 2ae8ceb4eef451cc869982ef09266d33715c60e9)