Adapt to new global neutron upper constraint and adjust hacking version
This patch solves multiple problems to fix gate:

1. Neutron constrained the version of hacking < 1.2.0, but since then
   the unit tests fails with:

ERROR: Double requirement given: hacking<1.2.0,>=1.1.0 (from -ri https://opendev.org/openstack/neutron/raw/branch/master/test-requirements.txt (line 4)) (already in hacking>=1.1.0 (from -r [..]networking-powervm/test-requirements.txt (line 4)), name='hacking')

   So let's simply use the same constraint as set in neutron.

2. neutron was added to upper constraints in openstack/requirements
   stable branches (I8e95dc48b8ba2a7e16f1d34eb5ad0e87a3e96f4f), which
   causes failure due to conflict with tox targets installing neutron
   directly from git:

ERROR: Could not satisfy constraints for 'neutron': installation from path or url cannot be constrained to a version

   Most of the zuul templates used in the .zuul.yaml marks neutron as
   required project except lower-constraint job. Let's make that also
   install neutron. Also add neutron to requirements.txt.

Note(elod.illes): by removing editable git installation of neutron from
tox and adding it to requirements.txt involves that tests in Zuul will
run against latest stable state, but locally the test will run against
latest release from stable/* of neutron. So in short: they test
different things.

Change-Id: Ic4d97db6c947264806e5ef9e35f21f764cbecf46
(cherry picked from commit a00fc731b14bd3ef953fe4cffdc74c8e441c0e13)